# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/guamp/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),guamp)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,246d786c208f80039c3ed19ffe713e99891c5eb6)
$(call add-radio-file-sha1-checked,radio/modem.img,d3273c6f57b7d1bb85f3db6e5c08889fa9acb0f2)
$(call add-radio-file-sha1-checked,radio/abl.img,4e7461baaf965371768846a03d809f6f6afbf2bd)
$(call add-radio-file-sha1-checked,radio/devcfg.img,958c5a1fb9da5c1c7647fd333d2ea970ed1de950)
$(call add-radio-file-sha1-checked,radio/dsp.img,a4d96325a5d65cc91374e29ba29d7bbf19f50bd7)
$(call add-radio-file-sha1-checked,radio/fsg.img,08e0b9e1a76d71b0dd8c9eb77db07a352ee4d3d7)
$(call add-radio-file-sha1-checked,radio/hyp.img,19f20b608d08f05e94d4c36063d57d79684b8b30)
$(call add-radio-file-sha1-checked,radio/keymaster.img,3724cbcc190edbb77862d1bece9bc958ab59754b)
$(call add-radio-file-sha1-checked,radio/logo.img,fee4c88d31d3cd99eca11b2a16156234baf6097c)
$(call add-radio-file-sha1-checked,radio/prov.img,b31cb964e68de57e593c1785fed9be6adb52e52a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,5ecd98e159ba20ea9c83b17fbdc1ac087b375738)
$(call add-radio-file-sha1-checked,radio/rpm.img,ba54ddaae09c93e418e86b31ad71d895590703c9)
$(call add-radio-file-sha1-checked,radio/storsec.img,89247e7326287b4a876e61bba62c9ef09f16ec16)
$(call add-radio-file-sha1-checked,radio/tz.img,177485ea5df29fe8a4d346b4b2d4cf6ba9de1ed8)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,2b3e639f151f36a52f1609d7f05c3aa50ee7855c)
$(call add-radio-file-sha1-checked,radio/xbl.img,71e6e8a8973ee93e1180fc78e1d8ae136457d771)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,6616725957a850132146937b057ee61cad5fc014)

endif
